cart/urls.py
from django.urls import path

from . import views

app_name='cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('cart/add/<int:ingredient_id>/', views.cart_add, name='cart_add'),
    path('cart/remove/<int:ingredient_id>/', views.cart_remove, name='cart_remove'),
    path('cart/cocktail_all_ingredients_add/<int:cocktail_id>/', views.cocktail_all_ingredients_add,
         name='cocktail_all_ingredients_add'),
]

config/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.urls import path

import orders
from shop import views
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    # shop and cocktail_base
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('all_ingredients/', views.all_ingredients, name='all_ingredients'),
    path('cocktail/<int:cocktail_id>/', views.cocktail_detail, name='cocktail_detail'),
    path('ingredient/<int:ingredient_id>/', views.ingredient_detail, name='ingredient_detail'),

    # cart
    path('cart/', include('cart.urls', namespace='cart')),

    # orders
    path('orders/', include('orders.urls', namespace='orders')),

    # authorization
    path('singup/', views.singupuser, name='singupuser'),
    path('logout/', views.logoutuser, name='logoutuser'),
    path('login/', views.loginuser, name='loginuser'),

    #search
    path('search/', include('search.urls', namespace='search')),

    ]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/cocktail_base/cocktail_detail.html
{% extends "shop/base.html" %}
{% load static %}

{% block content %}

<div class="ingredient-card" style="margin-bottom:24px; padding:20px">
    <h3>{{ cocktail.title }}</h3>
    <div class="row">
        <div class="col-2" style="display: flex;align-items: center">
            <div class="cocktail-image">
                <img src="{{ cocktail.image.url }}" style="max-width:150px; max-height:250px">
            </div>
        </div>
        <div class="col-10 row" style="flex-direction: row; display: flex; flex-wrap: wrap;">
            {% for ingredients in cocktail.ingredients.all %}
            <div class="col-4" style="display: flex; flex-direction: column; align-items: center; margin-bottom:16px; text-align:center;">
                {% if user.is_authenticated %}
                <a href="{% url 'ingredient_detail' ingredients.id %}">
                    <h7>{{ ingredients.title }}</h7>
                </a>
                {% else %}
                    <h7>{{ ingredients.title }}</h7>
                {% endif %}

                <img style="border-radius:24px" src="{{ ingredients.image.url }}" height=85px width=85px>
            </div>
            {% endfor %}
        </div>
    </div>
</div>

<p> {{ cocktail.recipe| linenumbers | linebreaks }}</p>

{% if user.is_authenticated %}
    <div style="text-align: end;">
    <a href="{% url 'cart:cocktail_all_ingredients_add' cocktail.id %}" class="btn btn-primary styled-button">
        <img src="http://127.0.0.1:8000/static/shop/add_cart.png" class="add-cart-img">
    </a>
    </div>
{% endif %}

{% endblock %}