cart/urls.py
from django.urls import path

from . import views

app_name='cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('cart/add/<int:ingredient_id>/', views.cart_add, name='cart_add'),
    path('cart/remove/<int:ingredient_id>/', views.cart_remove, name='cart_remove'),
    path('cart/cocktail_all_ingredients_add/<int:cocktail_id>/', views.cocktail_all_ingredients_add,
         name='cocktail_all_ingredients_add'),
]

config/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.urls import path

import orders
from shop import views
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    # shop and cocktail_base
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('all_ingredients/', views.all_ingredients, name='all_ingredients'),
    path('cocktail/<int:cocktail_id>/', views.cocktail_detail, name='cocktail_detail'),
    path('ingredient/<int:ingredient_id>/', views.ingredient_detail, name='ingredient_detail'),

    # cart
    path('cart/', include('cart.urls', namespace='cart')),

    # orders
    path('orders/', include('orders.urls', namespace='orders')),

    # authorization
    path('singup/', views.singupuser, name='singupuser'),
    path('logout/', views.logoutuser, name='logoutuser'),
    path('login/', views.loginuser, name='loginuser'),

    #search
    path('search/', include('search.urls', namespace='search')),

    ]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from . import views

app_name='orders'

urlpatterns = [
    path('orders/create', views.order_create, name='order_create'),
    path('all_orders/', views.all_orders, name='all_orders'),
    path('order_detail/<int:order_id>', views.order_detail, name='order_detail'),
]

search/urls.py
from django.urls import path

from . import views

app_name='search'

urlpatterns = [
    path('', views.search_cocktail, name='search_cocktail'),
    path('ingredient/', views.search_ingredient, name='search_ingredient'),
]

shop/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    title = models.CharField(max_length=200, db_index=True)

    class Meta:
        ordering = ('title',)
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.title


class Ingredient(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    title = models.CharField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='media/ingredient/', blank=False)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.PositiveIntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('title',)
        verbose_name = 'Ingredient'
        verbose_name_plural = 'Ingredients'

    def get_absolute_url(self):
        return reverse('ingredient_detail',
                       args=[self.id])

    def __str__(self):
        return self.title


class Cocktail(models.Model):
    title = models.CharField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='media/cocktail/', blank=False)
    recipe = models.TextField(blank=True)
    ingredients = models.ManyToManyField(Ingredient)

    class Meta:
        ordering = ('title',)
        verbose_name = 'Cocktail'
        verbose_name_plural = 'Cocktails'

    def __str__(self):
        return self.title

    def __iter__(self):
        return iter(self.ingredients.all())

shop/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class MyAuthForm(UserCreationForm):

    class Meta:
        model=User
        fields = ('username', 'password1', 'password2')

    def __init__(self, *args, **kwargs):
        super(MyAuthForm, self).__init__(*args, **kwargs)

        self.fields['username'].widget.attrs['class'] = 'form-control'
        self.fields['password1'].widget.attrs['class'] = 'form-password'
        self.fields['password2'].widget.attrs['class'] = 'form-password'

shop/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from .models import Cocktail, Ingredient
from cart.forms import CartAddIngredientForm
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.db import IntegrityError
from django.contrib.auth import login, logout, authenticate


# SHOP
def home(request):
    cocktail = Cocktail.objects.all()
    return render(request, 'shop/home.html', {'cocktail': cocktail})


@login_required(login_url='http://127.0.0.1:8000/login/')
def all_ingredients(request):
    ingredient = Ingredient.objects.all()
    cart_ingredient_form = CartAddIngredientForm()
    return render(request, 'shop/shop.html', {'ingredient': ingredient,
                                              'cart_ingredient_form': cart_ingredient_form})


def cocktail_detail(request, cocktail_id):
    cocktail = get_object_or_404(Cocktail, pk=cocktail_id)
    return render(request, 'cocktail_base/cocktail_detail.html', {'cocktail': cocktail})


@login_required(login_url='http://127.0.0.1:8000/login/')
def ingredient_detail(request, ingredient_id):
    ingredient = get_object_or_404(Ingredient, pk=ingredient_id)
    cart_ingredient_form = CartAddIngredientForm()
    return render(request, 'shop/ingredient_detail.html', {'ingredient': ingredient,
                                                           'cart_ingredient_form': cart_ingredient_form})


# AUTH

def singupuser(request):
    if request.method == 'GET':
        return render(request, 'auth/singupuser.html', {'form': UserCreationForm()})
    else:
        if request.POST['password1'] == request.POST['password2']:
            try:
                user = User.objects.create_user(request.POST['username'], password=request.POST['password1'])
                user.save()
                login(request, user)
                return redirect('home')
            except IntegrityError:
                return render(request, 'auth/singupuser.html',
                              {'form': UserCreationForm(),
                               'error': 'That username has already been taken. Please choose new username'})
        else:
            return render(request, 'auth/singupuser.html', {'form': UserCreationForm(),
                                                            'error': 'Password did not match'})


def logoutuser(request):
    if request.method == 'POST':
        logout(request)
        return redirect('home')


def loginuser(request):
    if request.method == 'GET':
        return render(request, 'auth/loginuser.html', {'form': AuthenticationForm()})
    else:
        user = authenticate(request, username=request.POST['username'], password=request.POST['password'])
        if user is None:
            return render(request, 'auth/loginuser.html', {'form': AuthenticationForm(),
                                                           'error': 'User name and password did not match'})
        else:
            login(request, user)
            return redirect('home')

templates/shop/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'shop/style.css'%}?{% now 'U' %}">

    <link rel="icon" type="image/png" href="{% static 'shop/logo1.png' %}">

    <title>Shake_It</title>

</head>
<body style="background-image: url('/static/fon.jpg'); background-repeat: repeat;">

<nav id="topNav" class="navbar navbar-expand-md navbar-light">
    <div class="container" style="align-items: end;">
        <a class="navbar-brand" href="{% url 'home' %}">
            <img src="{% static 'shop/logo1.png' %}" class="logo-img" alt="Shake It">
        </a>
        <div class="collapse navbar-collapse text-center top-bar" id="navbarNav">
            <ul class="navbar-nav ml-auto">
                <li>
                    {% if user.is_authenticated %}
                    <div style="display: flex; align-items: center;">
                        Logged in as&nbsp<a href="{% url 'orders:all_orders' %}"><span style="font-weight: 700">{{ user.username }}</span></a>
                        <form action="{% url 'logoutuser' %}" method="POST">
                            {% csrf_token %}
                            <button style="margin-left:12px" type="submit" class="btn btn-primary styled-button">
                                Logout
                            </button>
                        </form>
                    </div>
                <li class="nav-item">
                    <a role="button" href="{% url 'cart:cart_detail' %}"
                       class="btn btn-primary styled-button ml-12">Cart
                    </a>
                </li>
                <li>
                    <a role="button" href="{% url 'all_ingredients' %}"
                       class="btn btn-primary styled-button ml-12">Shop
                    </a>
                </li>

                {% else %}
                <a href="{% url 'singupuser' %}" class="btn btn-primary styled-button ml-12">
                    Sing Up
                </a>
                <a href="{% url 'loginuser' %}" class="btn btn-primary styled-button ml-12">
                    Login
                </a>
                {% endif %}
                </li>
            </ul>
            {% if user.is_authenticated %}
            <div class="ml-auto" style="margin-top:12px">
                {% with total_items=cart|length %}
                {% if cart|length > 0 %}
                Your cart:
                <a href="{% url 'cart:cart_detail' %}">
                    {{ total_items }} item{{ total_items|pluralize }},
                    ${{ cart.get_total_price }}
                </a>
                {% else %}
                Your cart is empty.
                {% endif %}
                {% endwith %}
            </div>
            {% else %}
            <div class="ml-auto" style="margin-top:12px">
            Log in to access the store
            </div>
            {% endif %}
        </div>
    </div>
</nav>


<div class="container" style="background-color: #d7d7d7; padding: 24px; border-radius: 36px; width:900px">

    {% block content %}
    {% endblock %}

</div>

<!--<a style="margin-left: 12px" role="button" href="#" class="btn btn-primary styled-button">About Shop</a>-->
</body>

</html>

templates/shop/home.html
{% extends "shop/base.html" %}
{% load static %}

{% block content %}

<div class="search-container">
    <form action="{% url 'search:search_cocktail' %}" method="GET" class="align-items-center">
        <input class="search-input" name="query" placeholder="Enter cocktail or ingredient...">
        <button type="submit" class="btn btn-primary styled-button ml-12">
            Search
        </button>
    </form>
</div>

<div class="number-of-results">
    <h5>{{ number_of_results }}</h5>
</div>

{% for cocktail in cocktail %}

<div class="ingredient-card card-list-item">
    <div style="margin-bottom:24px">
        <a href="{% url 'cocktail_detail' cocktail.id %}"><h4>{{ cocktail.title }}<br></h4></a>
    </div>
    <div class='row'>
        <div class="col-2 cocktail-image-container">
            <div class="cocktail-image">
                <img src="{{ cocktail.image.url }}" style="max-width:100px"> <br>
            </div>
        </div>
        <p><br>
        <div class="col-10 row cocktail-ingredients-container">
        {% for ingredients in cocktail.ingredients.all %}
        <div class="col-3 cocktail-ingredient-container">
            <h7 style="text-align: center;">{{ ingredients.title }}</h7>
            <img class="cocktail-ingredient-image" src="{{ ingredients.image.url }}"><br>
        </div>
        {% endfor %}
    </div>
</div>
</div>

{% endfor %}


{% endblock %}

templates/shop/ingredient_detail.html
{% extends "shop/base.html" %}
{% load static %}

{% block content %}
    <div>
        <div class="ingredient-image-container">
            <img src="{{ ingredient.image.url }}" class="ingredient-image"><br>
        </div>
            <h4>{{ ingredient.title }}</h4>
        <p><h6>${{ ingredient.price }}</h6></p>
        <h6>{{ ingredient.description }}</h6>
        <form action="{% url 'cart:cart_add' ingredient.id %}" method="post">
            {{ cart_ingredient_form }}
            {% csrf_token %}
        <input class="btn btn-primary styled-button" type="submit" value="Add to cart">
        </form>
    </div>

{% endblock %}

templates/shop/shop.html
{% extends "shop/base.html" %}
{% load static %}
{% block content %}


<div class="row">
    <div class="search-container">
        <form action="{% url 'search:search_ingredient' %}" method="GET" class="align-items-center">
            <input name="query" placeholder="Enter ingredient..." class="search-input">
            <button type="submit" class="btn btn-primary styled-button ml-12">
                Search
            </button>
        </form>
    </div>
    <div class="number-of-results">
        <h5>{{ number_of_results }}</h5>
    </div>
    {% for ingredients in ingredient %}

    <div class="col-4" style="padding:4px">
        <div class="ingredient-card shop-ingredient-card-item">
            <a href="{% url 'ingredient_detail' ingredients.id %}">
                <h3 style="text-align: center;">{{ ingredients.title }}<br></h3>
            </a>
            <h5>${{ ingredients.price }} <br></h5>
            <img src="{{ ingredients.image.url }}" class="shop-ingredient-image">
            <div style="height:100%"></div>

            <div class="shop-form-margin">
                <form action="{% url 'cart:cart_add' ingredients.id %}" method="post">
                    {{ cart_ingredient_form }}
                    {% csrf_token %}
                    <input type="submit" value="Add to cart" class="btn btn-primary styled-button">
                </form>
            </div>

            <h6>{{ ingredients.category }}<br></h6>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}